site_name: Documentação Netbox
site_dir: ./site
site_url: https://docs.netbox.dev.br/
docs_dir: ./docs
repo_name: netbox-community/netbox
repo_url: https://github.com/netbox-community/netbox
theme:
  name: material
  custom_dir: docs/_theme/
  icon:
    repo: fontawesome/brands/github
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to Light Mode
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - navigation.footer
    - navigation.path
    - navigation.top
    - toc.follow
    - toc.integrate
plugins:
  - search
  - social
  #- mkdocstrings:
  #    handlers:
  #      python:
  #        setup_commands:
  #          - import os
  #          - import django
  #          - os.chdir('netbox/')
  #          - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "netbox.settings")
  #          - django.setup()
  #        options:
  #          heading_level: 3
  #          members_order: source
  #          show_root_heading: true
  #          show_root_full_path: false
  #          show_root_toc_entry: false
  #          show_source: false
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/netbox-community/netbox
    - icon: fontawesome/brands/slack
      link: https://netdev.chat/
    - icon: fontawesome/brands/telegram
      link: https://t.me/netboxbr
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9N3V4mpMXU
  homepage: https://netboxlabs.com
extra_css:
  - https://cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css
  - extra.css
markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - abbr
  - toc:
      permalink: true
      toc_depth: 4
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/@material-icons/iconfont/material-icons.min.js'
nav:
    - Introdução: 'introduction.md'
    - Características e Funções:
        - Instalações (Facilities): 'features/facilities.md'
        - Dispositivos & Cabeamento: 'features/devices-cabling.md'
        - Mapeamento de Energia: 'features/power-tracking.md'
        - IPAM (Endereçamento IP): 'features/ipam.md'
        - Gerência de VLANs: 'features/vlan-management.md'
        - L2VPN & Overlay: 'features/l2vpn-overlay.md'
        - Circuitos: 'features/circuits.md'
        - Wireless (Wi-Fi): 'features/wireless.md'
        - Virtualização: 'features/virtualization.md'
        - Locação (Tenancy): 'features/tenancy.md'
        - Contactos: 'features/contacts.md'
        - Pesquisa (Search): 'features/search.md'
        - Dados de Contexto: 'features/context-data.md'
        - Logging de Mudanças: 'features/change-logging.md'
        - Journaling: 'features/journaling.md'
        - Autenticação & Permissões: 'features/authentication-permissions.md'
        - Integrações & API: 'features/api-integration.md'
        - Customização: 'features/customization.md'
    - Instalação & Upgrade:
        - Instalando o NetBox: 'installation/index.md'
        - 1. PostgreSQL: 'installation/1-postgresql.md'
        - 2. Redis: 'installation/2-redis.md'
        - 3. NetBox: 'installation/3-netbox.md'
        - 4. Gunicorn: 'installation/4-gunicorn.md'
        - 5. Servidor HTTP: 'installation/5-http-server.md'
        - 6. LDAP (Opcional): 'installation/6-ldap.md'
        - Fazendo o Upgrade do NetBox: 'installation/upgrading.md'
    - Começando com o NetBox:
        - Planejamento: 'getting-started/planning.md'
        - Populando o NetBox com Dados: 'getting-started/populating-data.md'
    - Configuração:
        - Configurando o NetBox: 'configuration/index.md'
        - Parâmetros Obrigatórios: 'configuration/required-parameters.md'
        - Sistema: 'configuration/system.md'
        - Segurança: 'configuration/security.md'
        - Autenticação Remota: 'configuration/remote-authentication.md'
        - Dados & Validação: 'configuration/data-validation.md'
        - Valores Padrão (Default): 'configuration/default-values.md'
        - Registro de Erros: 'configuration/error-reporting.md'
        - Plugins: 'configuration/plugins.md'
        - NAPALM: 'configuration/napalm.md'
        - Data & Hora: 'configuration/date-time.md'
        - Diversos (Miscellaneous): 'configuration/miscellaneous.md'
        - Desenvolvimento: 'configuration/development.md'
    - Customização:
        - Campos Customizados: 'customization/custom-fields.md'
        - Links Customizados: 'customization/custom-links.md'
        - Validação Customizada: 'customization/custom-validation.md'
        - Exportação de Templates: 'customization/export-templates.md'
        - Relatórios (Reports): 'customization/reports.md'
        - Scripts Customizados: 'customization/custom-scripts.md'
    - Integrações:
        - API REST: 'integrations/rest-api.md'
        - API GraphQL: 'integrations/graphql-api.md'
        - Webhooks: 'integrations/webhooks.md'
        - NAPALM: 'integrations/napalm.md'
        - Métricas do Prometheus: 'integrations/prometheus-metrics.md'
    - Plugins:
        - Usando Plugins: 'plugins/index.md'
        - Desenvolvendo Plugins:
            - Começando: 'plugins/development/index.md'
            - Modelos: 'plugins/development/models.md'
            - Visualizações (Views): 'plugins/development/views.md'
            - Navegação: 'plugins/development/navigation.md'
            - Templates: 'plugins/development/templates.md'
            - Tabelas: 'plugins/development/tables.md'
            - Formulários: 'plugins/development/forms.md'
            - Filtros & Grupos de Filtro: 'plugins/development/filtersets.md'
            - Pesquisa (Search): 'plugins/development/search.md'
            - API REST: 'plugins/development/rest-api.md'
            - API GraphQL: 'plugins/development/graphql-api.md'
            - Tarefas de Fundo (Background): 'plugins/development/background-tasks.md'
            - Mudanças Pendentes (Staged): 'plugins/development/staged-changes.md'
            - Exceções: 'plugins/development/exceptions.md'
    - Administração:
        - Autenticação:
            - Visão Geral: 'administration/authentication/overview.md'
            - Microsoft Azure AD: 'administration/authentication/microsoft-azure-ad.md'
            - Okta: 'administration/authentication/okta.md'
        - Permissões: 'administration/permissions.md'
        - Registro de Erros: 'administration/error-reporting.md'
        - Housekeeping: 'administration/housekeeping.md'
        - Replicando o NetBox: 'administration/replicating-netbox.md'
        - NetBox Shell: 'administration/netbox-shell.md'
    - Modelos de Dados:
        - Circuitos:
            - Circuito: 'models/circuits/circuit.md'
            - Terminação de Circuito: 'models/circuits/circuittermination.md'
            - Tipo de Circuito: 'models/circuits/circuittype.md'
            - Fornecedor (Provider): 'models/circuits/provider.md'
            - Rede do Fornecedor (Provider): 'models/circuits/providernetwork.md'
        - DCIM (Gerenciamento de Infraestrutura):
            - Cabos: 'models/dcim/cable.md'
            - ConsolePort: 'models/dcim/consoleport.md'
            - ConsolePortTemplate: 'models/dcim/consoleporttemplate.md'
            - ConsoleServerPort: 'models/dcim/consoleserverport.md'
            - ConsoleServerPortTemplate: 'models/dcim/consoleserverporttemplate.md'
            - Device: 'models/dcim/device.md'
            - DeviceBay: 'models/dcim/devicebay.md'
            - DeviceBayTemplate: 'models/dcim/devicebaytemplate.md'
            - DeviceRole: 'models/dcim/devicerole.md'
            - DeviceType: 'models/dcim/devicetype.md'
            - FrontPort: 'models/dcim/frontport.md'
            - FrontPortTemplate: 'models/dcim/frontporttemplate.md'
            - Interface: 'models/dcim/interface.md'
            - InterfaceTemplate: 'models/dcim/interfacetemplate.md'
            - InventoryItem: 'models/dcim/inventoryitem.md'
            - InventoryItemRole: 'models/dcim/inventoryitemrole.md'
            - InventoryItemTemplate: 'models/dcim/inventoryitemtemplate.md'
            - Location: 'models/dcim/location.md'
            - Manufacturer: 'models/dcim/manufacturer.md'
            - Module: 'models/dcim/module.md'
            - ModuleBay: 'models/dcim/modulebay.md'
            - ModuleBayTemplate: 'models/dcim/modulebaytemplate.md'
            - ModuleType: 'models/dcim/moduletype.md'
            - Platform: 'models/dcim/platform.md'
            - PowerFeed: 'models/dcim/powerfeed.md'
            - PowerOutlet: 'models/dcim/poweroutlet.md'
            - PowerOutletTemplate: 'models/dcim/poweroutlettemplate.md'
            - PowerPanel: 'models/dcim/powerpanel.md'
            - PowerPort: 'models/dcim/powerport.md'
            - PowerPortTemplate: 'models/dcim/powerporttemplate.md'
            - Rack: 'models/dcim/rack.md'
            - RackReservation: 'models/dcim/rackreservation.md'
            - RackRole: 'models/dcim/rackrole.md'
            - RearPort: 'models/dcim/rearport.md'
            - RearPortTemplate: 'models/dcim/rearporttemplate.md'
            - Region: 'models/dcim/region.md'
            - Site: 'models/dcim/site.md'
            - SiteGroup: 'models/dcim/sitegroup.md'
            - VirtualChassis: 'models/dcim/virtualchassis.md'
            - VirtualDeviceContext: 'models/dcim/virtualdevicecontext.md'
        - Extras:
            - Branch: 'models/extras/branch.md'
            - ConfigContext: 'models/extras/configcontext.md'
            - CustomField: 'models/extras/customfield.md'
            - CustomLink: 'models/extras/customlink.md'
            - ExportTemplate: 'models/extras/exporttemplate.md'
            - ImageAttachment: 'models/extras/imageattachment.md'
            - JournalEntry: 'models/extras/journalentry.md'
            - SavedFilter: 'models/extras/savedfilter.md'
            - StagedChange: 'models/extras/stagedchange.md'
            - Tag: 'models/extras/tag.md'
            - Webhook: 'models/extras/webhook.md'
        - IPAM (Endereçamento IP):
            - ASN: 'models/ipam/asn.md'
            - Agregado de Prefixos (Aggregate): 'models/ipam/aggregate.md'
            - FHRPGroup: 'models/ipam/fhrpgroup.md'
            - FHRPGroupAssignment: 'models/ipam/fhrpgroupassignment.md'
            - IPAddress: 'models/ipam/ipaddress.md'
            - IPRange: 'models/ipam/iprange.md'
            - L2VPN: 'models/ipam/l2vpn.md'
            - L2VPNTermination: 'models/ipam/l2vpntermination.md'
            - Prefix: 'models/ipam/prefix.md'
            - RIR: 'models/ipam/rir.md'
            - Role: 'models/ipam/role.md'
            - RouteTarget: 'models/ipam/routetarget.md'
            - Service: 'models/ipam/service.md'
            - ServiceTemplate: 'models/ipam/servicetemplate.md'
            - VLAN: 'models/ipam/vlan.md'
            - VLANGroup: 'models/ipam/vlangroup.md'
            - VRF: 'models/ipam/vrf.md'
        - Locação (Tenancy):
            - Contact: 'models/tenancy/contact.md'
            - ContactGroup: 'models/tenancy/contactgroup.md'
            - ContactRole: 'models/tenancy/contactrole.md'
            - Tenant: 'models/tenancy/tenant.md'
            - TenantGroup: 'models/tenancy/tenantgroup.md'
        - Virtualização (Virtualization):
            - Cluster: 'models/virtualization/cluster.md'
            - ClusterGroup: 'models/virtualization/clustergroup.md'
            - ClusterType: 'models/virtualization/clustertype.md'
            - VMInterface: 'models/virtualization/vminterface.md'
            - VirtualMachine: 'models/virtualization/virtualmachine.md'
        -  Wireless (Wi-Fi):
            - WirelessLAN: 'models/wireless/wirelesslan.md'
            - WirelessLANGroup: 'models/wireless/wirelesslangroup.md'
            - WirelessLink: 'models/wireless/wirelesslink.md'
    - Referência:
        - Filtros: 'reference/filtering.md'
        - Condições: 'reference/conditions.md'
        - Markdown: 'reference/markdown.md'
    - Desenvolvimento:
        - Introdução: 'development/index.md'
        - Começando: 'development/getting-started.md'
        - Guia de Estilo (CSS): 'development/style-guide.md'
        - Modelos: 'development/models.md'
        - Adicionando Modelos: 'development/adding-models.md'
        - Extendendo Modelos: 'development/extending-models.md'
        - Sinais (Signals): 'development/signals.md'
        - Pesquisa (Search): 'development/search.md'
        - Registro das Aplicações: 'development/application-registry.md'
        - Preferências do Usuário: 'development/user-preferences.md'
        - Interface Web: 'development/web-ui.md'
        - Checklist da Versão (Release): 'development/release-checklist.md'
        - git Cheat Sheet: 'development/git-cheat-sheet.md'
    - Notas da Versão (Release Notes):
        - Resumo: 'release-notes/index.md'
        - Versão 3.4: 'release-notes/version-3.4.md'
        - Versão 3.3: 'release-notes/version-3.3.md'
        - Versão 3.2: 'release-notes/version-3.2.md'
        - Versão 3.1: 'release-notes/version-3.1.md'
        - Versão 3.0: 'release-notes/version-3.0.md'
        - Versão 2.11: 'release-notes/version-2.11.md'
        - Versão 2.10: 'release-notes/version-2.10.md'
        - Versão 2.9: 'release-notes/version-2.9.md'
        - Versão 2.8: 'release-notes/version-2.8.md'
        - Versão 2.7: 'release-notes/version-2.7.md'
        - Versão 2.6: 'release-notes/version-2.6.md'
        - Versão 2.5: 'release-notes/version-2.5.md'
        - Versão 2.4: 'release-notes/version-2.4.md'
        - Versão 2.3: 'release-notes/version-2.3.md'
        - Versão 2.2: 'release-notes/version-2.2.md'
        - Versão 2.1: 'release-notes/version-2.1.md'
        - Versão 2.0: 'release-notes/version-2.0.md'