site_name: Documentação Netbox
site_dir: ./site
docs_dir: ./docs
theme:
  name: material
  language: pt-BR
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - navigation.footer
    - navigation.path
    - navigation.top
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
    logo: assets/favicon.ico
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/netbox-community/netbox
    - icon: fontawesome/brands/slack
      link: https://netdev.chat/
    - icon: fontawesome/brands/telegram
      link: https://t.me/netboxbr
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9N3V4mpMXU
  homepage: https://netboxlabs.com
repo_url: https://github.com/netbox-community/netbox
plugins:
  - search
  - social
extra_css:
  - https://cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css
markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - abbr
  - toc:
      permalink: true
      toc_depth: 4
  - tables
  - footnotes