name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache  
      - run: sudo apt install python3-pip python3-apt python3-cffi python3-brotli -y
      - run: sudo apt install libharfbuzz0b libpangoft2-1.0-0 libgtk-3-dev gcc -y
      - run: sudo pip3 install mkdocs-material
      - run: sudo pip3 install mkdocs-minify-plugin
      - run: sudo pip3 install mkdocs-redirects
      - run: sudo pip3 install pillow cairosvg
      - run: sudo mkdocs gh-deploy --force
